# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_activity_mailchimp_new:
    pattern: /activity/mailchimp/new
    defaults: { _controller: campaignchain.activity.controller.mailchimp.schedule:newAction }

campaignchain_activity_mailchimp_edit:
    pattern: /activity/mailchimp/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.mailchimp.schedule:editAction }

campaignchain_activity_mailchimp_edit_modal:
    pattern: /modal/activity/mailchimp/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.mailchimp.schedule:editModalAction }

campaignchain_activity_mailchimp_edit_api:
    pattern: /api/private/activity/mailchimp/byactivity/{id}/edit
    defaults: { _controller: campaignchain.activity.controller.mailchimp.schedule:editApiAction }
    options:
        expose: true

campaignchain_activity_mailchimp_read:
    pattern: /activity/mailchimp/{id}
    defaults: { _controller: campaignchain.activity.controller.mailchimp.schedule:readAction }

campaignchain_activity_mailchimp_preview:
    pattern: /activity/mailchimp/preview/{id}
    defaults: { _controller: CampaignChainActivityMailChimpBundle:MailChimp:preview }